"""user table added

Revision ID: 019fa2855c1b
Revises: b68662dd39f6
Create Date: 2022-08-28 20:07:03.384633

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '019fa2855c1b'
down_revision = 'b68662dd39f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=256), nullable=True),
                    sa.Column('email', sa.String(length=256), nullable=True),
                    sa.Column('password',
                              sqlalchemy_utils.types.password.PasswordType(
                                  max_length=1137,
                                  postgresql_using='password::bytea'),
                              nullable=True),
                    sa.Column('permission',
                              sa.String(length=256), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
